name: CI tests workflow

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run eslint
      - name: Run tests
        run: npm run test